HW01
Soykaa/software-design-2022-hse pull request #1
Opened 2022-01-23 19:43 UTC by Soykaa

Выполнили:

- Жемчужина Елизавета (@lizazhemchuzhina)
- Сунко Елена (@LenSunko01)
- Кириллова Евгения (@JaneKirillova)
- Иценко Екатерина (@Soykaa)

2022-01-24 10:43 UTC, yurii-litvinov requested changes
Ещё небольшой комментарий по диаграммам: диаграмма выглядит почти как диаграмма классов UML, тогда стоило parent-child на концах ассоциаций не писать, а рисовать ромбики, как вот тут: https://www.uml-diagrams.org/aggregation.html

Но вообще диаграммам классов вас ещё не учили, поэтому это на будущее (справедливости ради, и типы в UML пишутся через двоеточие после имени, а не как в Java, и Extends над стрелкой наследования не пишется).

В целом очень годно для начала — не со всеми решениями я согласен, но почти про всё подумали.

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +По умолчанию поиск внешних команд осуществляется в _usr_ и _usr/bin_.
Обычно — по списку директорий из переменной окружения PATH. А так оно у вас под Windows будет плохо работать

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    * токены разделяются по пробелам. При этом, если внутри входа содержится строка в одинарных или двойных кавычках, то она целиком выделяется в один токен
- Тогда `a|b` разберётся в один токен, что может быть неожиданно. В принципе, хозяин — барин, и вы можете требовать пробел между лексическими единицами, но стоит это явно отразить в документации, и настоящие шеллы так не делают
- Это может быть не так просто реализовать, стоило бы описать подробнее, как именно производится парсинг.

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    *  набор символов после него определяется как имя переменной, для которой нужно выполнить подстановку
После него и до...? Например, ` $x ` понятно, а ` $x$y `, если понимать написанное буквально, уже как-то не очень.

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    *  аналогичные действия выполняются для всех знаков `$` в токене, после чего токен становится _FullyProcessed_
- А он не может :) Поменять класс в рантайме, наверное, можно, если у вас JavaScript, но обычно должен быть механизм, который объект одного класса заменит на объект другого
- А зачем два отдельных класса для FullyProcessedToken и  WeaklyProcessedToken, и отдельно метод type? type выглядит как code smell "тэг типа", и кажется, что на самом деле только он и нужен (вроде никаких полиморфных вызовов или вообще разного состояния/поведения у этих классов нет).
- А если в результате образуются новые токены? Например, 
  ```
  x="a"
  echo a$x
  ```
  Следуя логике лексера, должно получиться три токена, а получится два. Тут это, может, и не плохо, но если допустить возможность существования пайпов без пробелов, то может получиться совсем печаль. Или вот так:
  ```
  x=echo 123
  $x
  ```
  Если парсер получит один токен, ему будет не догадаться, что это команда с аргументом.

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +* `String get(String)` - метод, который проверяет, что переданное название переменной существует, и если это так, то возвращает её значение, иначе `null`
Сегодня на паре как раз обсудим, что "не возвращайте null" — одно из важных правил хорошего кода :)

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    * отдельно обрабатывается случай, в котором название команды содержит знак `=`. В этом случае названием команды является _environment_, а аргументы получаются из токена со знаком `=`: набор симво
Тут вы наоборот, требуете отсутствия пробела перед "=" (что вполне ок, но, опять-таки, стоит явно задокументировать). И поскольку разбор "=" выполняется, как я понял, в рамках одного токена, в правой части не может быть ни кавычек, ни пробелов (они в следующий токен уйдут). Что существенно снижает полезность подстановки — например, объявить переменную, содержащую все опции компилятора, и передавать их компилятору в нескольких местах — уже не получится

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +Хранит внутри себя список названий и соответсвующие конструкторы.
```suggestion
Хранит внутри себя список названий и соответствующие конструкторы.
```

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +* `IOStream stdout`
Ну, поля у интерфейса — это как-то не канонично, хотя понятно, что имелось в виду (и если язык поддерживает свойства, даже вполне реализуемо). Так что можно это не править :)

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +* _**ExitCommand**_ - команда, которая принимает на вход объект класса и вызывает у него метод `exit()`
```suggestion
* _**ExitCommand**_ - команда, которая принимает на вход объект класса CLI и вызывает у него метод `exit()`
```
Вопрос лишь, откуда она про него знает. И это не показано на диаграмме.

2022-01-24 10:43 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    5. У каждого элемента в этом списке вызывается метод `execute()`. То, что будет находиться у последнего элемента в `OutputStream` и будет результатом выполнения программы
- Кажется, у вас так нигде и не описано, кто создаёт потоки, кто связывает потоки команд в пайпе, и вообще, параллельно или последовательно они работают
- CLI не слишком умным получится? На нём: 
  - инициализация системы
  - Read-Execute-Print-Loop
  - Координация всех остальных классов
  - Обработка exit
  - Да ещё и вся работа с пайпами

2022-01-27 22:33 UTC, Soykaa commented on hw01/documentationCLI.md
> +По умолчанию поиск внешних команд осуществляется в _usr_ и _usr/bin_.
Исправили, теперь поиск внешних команд осуществляется в директориях, перечисленных в переменной окружения PATH (формат хранения путей одинаковый => от платформы зависеть действительно не должно)

2022-01-27 22:37 UTC, Soykaa commented on hw01/documentationCLI.md
> +    * токены разделяются по пробелам. При этом, если внутри входа содержится строка в одинарных или двойных кавычках, то она целиком выделяется в один токен
> настоящие шеллы так не делают

Да, не знали)
Отразили в описании парсинга деление как по пробелам, так и по пайпам (вроде этого достаточно?)

2022-01-27 22:40 UTC, Soykaa commented on hw01/documentationCLI.md
> +    *  набор символов после него определяется как имя переменной, для которой нужно выполнить подстановку
`$x$y` выделится лексером в один токен, т.к. нет пробелов или пайпов, по которым разделение. Затем уже задача `PreProcessor` подставить значения переменных среды. 
Логика выделения названия переменной следующая: идем вправо до символа `$`, `|` или `' '` (судя по нашим экспериментам в реальном шелле, там выделение ровно такое)

2022-01-27 22:44 UTC, Soykaa commented on hw01/documentationCLI.md
> +    *  аналогичные действия выполняются для всех знаков `$` в токене, после чего токен становится _FullyProcessed_
> А он не может :) Поменять класс в рантайме, наверное, можно, если у вас JavaScript, но обычно должен быть механизм, который объект одного класса заменит на объект другого

Тут под заменой имелось в вида создание нового объекта, то есть на вход получили список из токенов, часть из которых WeaklyProcessed, а часть FullyProcessed. У тех где WeaklyProcessed получили строку, куда надо подставить, туда подставили, после этого уже с новой строкой создали объект FullyProcessed.

> А зачем два отдельных класса для FullyProcessedToken и WeaklyProcessedToken, и отдельно метод type?

Согласны, на данном этапе overdesign. Исправили на класс `Token` с полем `type`.

2022-01-27 22:48 UTC, Soykaa commented on hw01/documentationCLI.md
> +    *  аналогичные действия выполняются для всех знаков `$` в токене, после чего токен становится _FullyProcessed_
> А если в результате образуются новые токены? <...>

Команды `x="a"` и `echo a$x` придут в разных строках и будут обработаны по-отдельности (т.е. мы хотим построчную обработку, а не всего скопа целиком). Соответственно, в первом случае будет один токен `x="a"`, а во втором два токена: `echo` и `a$x`. В случае второго `PreProcessor` подставит на место `$x` значение переменной окружения `x` и в итоге получится токен `avalue` (пробелов или чего-то еще не предполагается).
В случае `x=echo 123` шелл ругается, так как не поддерживает запись в переменную среды выражений с пробелов без кавычек. В нашей реализации будет такое же поведение, тоже не поддерживаем, считаем `123` уже началом следующего токена.

2022-01-27 22:49 UTC, Soykaa commented on hw01/documentationCLI.md
> +* `String get(String)` - метод, который проверяет, что переданное название переменной существует, и если это так, то возвращает её значение, иначе `null`
Fixed (но вообще, мы просто сначала делали по аналогии с подобным запросом в Java. Но после практики все прояснилось))

2022-01-27 22:52 UTC, Soykaa commented on hw01/documentationCLI.md
> +    * отдельно обрабатывается случай, в котором название команды содержит знак `=`. В этом случае названием команды является _environment_, а аргументы получаются из токена со знаком `=`: набор симво
Смотрели локально на работу шелла - в нем не поддерживаются пробелы до и после "=" (в документации отразили, делаем по аналогии). 
Разбор "=" в рамках одного токена, да, при этом кавычки использовать можно, так как они не являются началом следующего токена. Пробел вроде бы просто так использовать нельзя, он обязательно должен быть в кавычках, иначе это начало следующего токена (так в шелле сделано, и так же у нас).

2022-01-27 22:52 UTC, Soykaa commented on hw01/documentationCLI.md
> +Хранит внутри себя список названий и соответсвующие конструкторы.
Fixed

2022-01-27 22:53 UTC, Soykaa commented on hw01/documentationCLI.md
> +* `IOStream stdout`
Справедливо, подправили на абстрактный класс

2022-01-27 22:54 UTC, Soykaa commented on hw01/documentationCLI.md
> +* _**ExitCommand**_ - команда, которая принимает на вход объект класса и вызывает у него метод `exit()`
В `exit` будет передаваться ссылка на родительский класс (так как сам по себе `CommandBuilder` будет вызываться именно из него, то проблем возникнуть не должно). На диаграмме поправили.

2022-01-27 22:56 UTC, Soykaa commented on hw01/documentationCLI.md
> +    5. У каждого элемента в этом списке вызывается метод `execute()`. То, что будет находиться у последнего элемента в `OutputStream` и будет результатом выполнения программы
> Кажется, у вас так нигде и не описано, кто создаёт потоки, кто связывает потоки команд в пайпе, и вообще, параллельно или последовательно они работают

Подправили документацию. В `CommandBuilder` порядок, в котором передаются `CommandTokens` важен, он отвечает порядку следования команд в пайпе. Соответственно, при создании команды в `CommandBuilder` будет происходить их создание и связывание. На выход `CLI` получает последовательность `Command` и вызывает `execute` у них, здесь архитектура позволяет довольно просто перейти к параллельному исполнению, но мы решили использовать последовательное.

2022-01-27 22:59 UTC, Soykaa commented on hw01/documentationCLI.md
> +    5. У каждого элемента в этом списке вызывается метод `execute()`. То, что будет находиться у последнего элемента в `OutputStream` и будет результатом выполнения программы
> CLI не слишком умным получится?  <...>

Да, действительно, подправили. Можно на него переложить ответственность только за получение команд от пользователей (сюда же вывод `$`, как в шелле при ожидании команд, можно в будущем добавить вывод поддерживаемых команд на help и какое-нибудь красивое сообщение для пользователя при старте). И дополнительно вводится сущность `Executor`, который принимает строку от пользователя и в нужной последовательности вызывает `Lexer`, `PreProcessor`, `Parser`, `CommandBuilder`, исполнение команд.

2022-01-28 11:33 UTC, yurii-litvinov requested changes
Теперь почти всё ок, из важного надо только уточнить ещё немного про подстановки.

2022-01-28 11:33 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    5. У каждого элемента в этом списке вызывается метод `execute()`. То, что будет находиться у последнего элемента в `OutputStream` и будет результатом выполнения программы
Ага, теперь всё ок

2022-01-28 11:33 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    * Если встретили пробел, то заканчиваем текущий токен, начинаем набирать символы в следующий
Пробелы пропускаем же? А то тут можно понять неправильно. Хотя это придирка, конечно :)

2022-01-28 11:33 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    При этом для каждого токена данный метод определяет, нужно ли в нем выполнять подстановку (были ли использованы двойные кавычки), и в зависимости от этого определяется его тип (считаем, что подст
Или заключённого, но внутри двойных. `x=a ... echo "'$x'"` в bash выдаст `'a'`

2022-01-28 11:33 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    *  набор символов после него (и до символа `$`, `|` или `' '`) определяется как имя переменной, для которой нужно выполнить подстановку
Двойные кавычки, я думаю, тоже

2022-01-28 11:33 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    *  аналогичные действия выполняются для всех знаков `$` в токене, после чего токен становится _FullyProcessed_
>Тут под заменой имелось в вида создание нового объекта

Ну да, это замечание было скорее про то, что надо написать, кто это делает и как. Теперь, как я понимаю, сам токен просто меняет себе поле type. Или нет?

> В случае второго PreProcessor подставит на место $x значение переменной окружения x и в итоге получится токен avalue (пробелов или чего-то еще не предполагается).

Да, это разумно.

>В случае x=echo 123 шелл ругается, так как не поддерживает запись в переменную среды выражений с пробелов без кавычек.

Зато тогда тут может быть неконсистентно: `x="echo 123" ... $x`, в bash выведет 123, у вас --- "неизвестная команда echo 123", как я понимаю. Иное дело, что у вас, в отличие от bash, кавычки, наверное, подставляются без изменений, так что поведение корректно --- "echo 123" в кавычках и bash бы не понравилось. Но это вопрос скорее концептуальный --- если подстановка никогда-никогда не приводит к перетокенизации, стоит про это явно написать и как-то обосновать свой выбор, потому что в bash не так (зато в zsh, говорят, так).

И ещё стоит отдельно объяснить насчёт стратегии подстановки --- пока можем или один раз. Например,
```
x=$x
echo $x
```
(у вас ничего плохого не произойдёт, потому что подстановка в первой строке сразу даст пустую строку, но я могу из вредности в следующей домашке добавить требование поддержки `\$`, и тогда `x=\$x` может привести к подстановке строки `$x` вместо `$x` и случится печаль). Даже если это пока не важно, реализовать-то надо какую-то конкретную стратегию, и поскольку неудачный выбор может потом усложнить жизнь, её ввыбор должен быть зафиксирован в архитектуре.

2022-01-28 11:33 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    *  в случае, если соответствующая переменная среды не найдена, выбрасывается исключение
А bash пустую строку вставляет :)

2022-01-28 11:33 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +* `void set(String var, String val)` - метод, который сохраняет название переменной и ее значение. Если название уже существует, то перезаписывает значение
В коде не стоит сокращать имена --- написать их надо один раз, а читать, возможно, тысячи.

2022-01-28 11:33 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    * отдельно обрабатывается случай, в котором название команды содержит знак `=`. В этом случае названием команды является _environment_, а аргументы получаются из токена со знаком `=`: набор симво
Ага, у вас кавычки не граница токена, тогда да, разумно

2022-01-28 20:37 UTC, Soykaa commented on hw01/documentationCLI.md
> +    *  аналогичные действия выполняются для всех знаков `$` в токене, после чего токен становится _FullyProcessed_
> Ну да, это замечание было скорее про то, что надо написать, кто это делает и как. Теперь, как я понимаю, сам токен просто меняет себе поле type. Или нет?

Да, поле `type` является enum-ом, поэтому в нем просто поменяется значение. Уточнили в документации.

> Зато тогда тут может быть неконсистентно <...>

Нам показалось, что перетокенизация просто немного усложняет интуитивное понимание, т.к. часто тяжело понять, что получится на выходе. Т.е. в нашем понимании использование кавычек как раз обозначает, что аргумент рассматривается как единое целое, а не как набор из обособленных аргументов, поэтому, например, мы думали, что в этом случае bash и должен ругаться, так как ему передан один аргумент "echo 123", который обозначает название команды. В документации отразили :)

2022-01-28 20:39 UTC, Soykaa commented on hw01/documentationCLI.md
> +    *  аналогичные действия выполняются для всех знаков `$` в токене, после чего токен становится _FullyProcessed_
> И ещё стоит отдельно объяснить насчёт стратегии подстановки --- пока можем или один раз. <...>

Не совсем понятно, что имеется в виду:( в текущей реализации будет обработана строка `x=$x`, где будет попытка произвести подстановку на место `$x` значения переменной `x` (если такая переменная уже была объявлена ранее, то возьмем предыдущее значение, если нет, то ругнемся).

2022-01-28 20:42 UTC, Soykaa commented on hw01/documentationCLI.md
> +    * Если встретили пробел, то заканчиваем текущий токен, начинаем набирать символы в следующий
Да, пропускаем, причем все сразу, если их несколько. В документации отразили.

2022-01-28 20:42 UTC, Soykaa commented on hw01/documentationCLI.md
> +    При этом для каждого токена данный метод определяет, нужно ли в нем выполнять подстановку (были ли использованы двойные кавычки), и в зависимости от этого определяется его тип (считаем, что подст
Поправили :)

2022-01-28 20:43 UTC, Soykaa commented on hw01/documentationCLI.md
> +    *  набор символов после него (и до символа `$`, `|` или `' '`) определяется как имя переменной, для которой нужно выполнить подстановку
Ага, поправили

2022-01-28 20:44 UTC, Soykaa commented on hw01/documentationCLI.md
> +    *  в случае, если соответствующая переменная среды не найдена, выбрасывается исключение
Можно было бы и пустую, но, кажется, как правило это ошибка пользователя (пользователь думал, что задал значение переменной, а на самом деле нет), и хочется явно об этом сигнализировать

2022-01-28 20:44 UTC, Soykaa commented on hw01/documentationCLI.md
> +* `void set(String var, String val)` - метод, который сохраняет название переменной и ее значение. Если название уже существует, то перезаписывает значение
Исправили

2022-01-29 12:44 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2022-01-29 12:44 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    *  в случае, если соответствующая переменная среды не найдена, выбрасывается исключение
Да, разумно

2022-01-29 12:44 UTC, yurii-litvinov commented on hw01/documentationCLI.md
> +    *  аналогичные действия выполняются для всех знаков `$` в токене, после чего токен становится _FullyProcessed_
Ну, а если бы были разрешены эскейп-последовательности, то можно было бы сделать `x=\$x`, и дальше при подстановке, например, в `echo $x` вместо `$x` подставится строка `$x`, которая тоже как бы требует подстановки, и получаем бесконечную рекурсию. Того же эффекта, наверное, можно добиться, если отбрасывать одинарные кавычки при подстановке. 

С другой стороны, если бы да кабы... У вас ничего плохого пока произойти не может, так что ок (хотя хороший архитектор бы заранее обратил на это внимание — тем более что у вас недавно курс по формальным языкам был, как я понял).

2022-02-04 15:37 UTC, merged