Hw03: Реализация CLI, часть 2
Soykaa/software-design-2022-hse pull request #12
Opened 2022-02-08 13:07 UTC by JaneKirillova

Выполнили:

- Жемчужина Елизавета (@lizazhemchuzhina)
- Сунко Елена (@LenSunko01)
- Кириллова Евгения (@JaneKirillova)
- Иценко Екатерина (@Soykaa)

2022-02-10 11:26 UTC, yurii-litvinov requested changes
- Лучше было пуллреквест в hw2 делать, чтобы показывалась только разница
- Несколько параноидальный error reporting:
  ```
  $ echo '"'
  Incorrect quotes
  ```
  Это вполне валидный кейс, мы пытаемся заэскейпить одну кавычку

Но в остальном всё хорошо, надо только немного поправить

2022-02-10 11:26 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/PreProcessor.java
> +        StringBuilder variableName = new StringBuilder();
var?

2022-02-10 11:26 UTC, yurii-litvinov commented on src/test/java/ru/hse/software/design/ParserTests.java
> +        Token command = new Token("command", Type.FULLY_PROCESSED);
В тестах тоже можно повсюду var-ов навставлять, возможно, будет лучше

2022-02-10 11:26 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/WCCommand.java
> +            output = numLines + " " + " " + numWords + " " + numBytes;
Кстати, а зачем два пробела? И, кстати, настоящий wc вроде использует табуляции.

2022-02-11 12:59 UTC, Soykaa commented on src/main/java/ru/hse/software/design/PreProcessor.java
> +        StringBuilder variableName = new StringBuilder();
ага, fixed

2022-02-11 12:59 UTC, Soykaa commented on src/test/java/ru/hse/software/design/ParserTests.java
> +        Token command = new Token("command", Type.FULLY_PROCESSED);
fixed

2022-02-11 13:00 UTC, Soykaa commented on src/main/java/ru/hse/software/design/commands/WCCommand.java
> +            output = numLines + " " + " " + numWords + " " + numBytes;
Исправили на табуляцию

2022-02-11 13:04 UTC, Soykaa commented
Lexer и PreProcessor поправили, теперь случай с `echo '"'` нормально отработает.

2022-02-11 14:36 UTC, yurii-litvinov approved these changes
С этой частью теперь всё хорошо, зачтена

2022-02-11 14:36 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/Environment.java
> +    /**
```suggestion
    }

    /**
```

2022-02-11 18:12 UTC, merged