HW04: Реализация Grep
Soykaa/software-design-2022-hse pull request #16
Opened 2022-02-18 20:10 UTC by Soykaa

Выполнили:
- Жемчужина Елизавета (@lizazhemchuzhina)
- Сунко Елена (@LenSunko01)
- Кириллова Евгения (@JaneKirillova)
- Иценко Екатерина (@Soykaa)

2022-02-20 19:06 UTC, yurii-litvinov requested changes
По диаграмме:
- Вместо `List<что-то-там>` более архитектурно писать `что-то-там [*]`, вместо `Optional<что-то-там>` --- `что-то-там [0..1]`. Не надо привязываться к конкретному контейнеру раньше времени (разве что с Map это ок, потому что сам UML их не умеет --- точнее, умеет квалифицированные ассоциации, но это не всегда подходит).
- Что-то я сомневаюсь, что всё, что у вас нарисовано как ассоциации, действительно ассоциации. Например, не исключено, что Parser `<<creates>>` CommandToken, и между ними просто зависимость (пунктиром). Ассоциация подразумевает поле.

Кстати, при запуске `gradlew test` оно просто пишет, что всё хорошо. А вроде как несложно сделать так, чтобы оно писало статистику по тестовому запуску --- сколько тестов всего, сколько прошло, сколько проигнорировано.

А ещё с `cat` что-то не то, `cat build.gradle | grep plugin` печатает весь build.gradle, а должен скармливать его следующей команде в пайпе.

И немного невнятные сообщения об ошибке:
```
$ grep -A test build.gradle
For input string: "test"
```

2022-02-20 19:06 UTC, yurii-litvinov commented on README.md
> +В случае, если имя переменно не введено, то есть после `$` следует один из символов `'`, `"`, `' '`, `|`, то подстановка выполнена не будет, символ `$` останется в токене
```suggestion
В случае, если имя переменной не введено, то есть после `$` следует один из символов `'`, `"`, `' '`, `|`, то подстановка выполнена не будет, символ `$` останется в токене
```

2022-02-20 19:06 UTC, yurii-litvinov commented on README.md
> +`grep <regular_expression> [file_name]` - выводит строчки файла `file_name`, в которыйх был найден паттерн `regular_expression`. В случае, если файл не задан, то паттерн ищется в строчках стандартног
```suggestion
`grep <regular_expression> [file_name]` - выводит строчки файла `file_name`, в которых был найден паттерн `regular_expression`. В случае, если файл не задан, то паттерн ищется в строчках стандартного ввода.
```

2022-02-20 19:06 UTC, yurii-litvinov commented on README.md
> +2. Для разбора аргументов, передаваемых команде, используется библиотека `Apache Commons CLI`, выбор в ее пользу был сделан из-за того, что с данной библиотекой мы уже знакомы и работали в другом про
Надо посмотреть что-то ещё и написать, что ещё смотрели. "Уже знакомы" может быть весомым аргументом в пользу выбора библиотеки, но выбор должен быть, и не из одного кандидата. Иначе это антипаттерн "Золотой молоток", а я, следуя вашей логике, должен писать исключительно на Паскале :)

2022-03-03 18:16 UTC, JaneKirillova commented on README.md
> +2. Для разбора аргументов, передаваемых команде, используется библиотека `Apache Commons CLI`, выбор в ее пользу был сделан из-за того, что с данной библиотекой мы уже знакомы и работали в другом про
добавили еще три варианта библиотек

2022-03-03 19:23 UTC, LenSunko01 commented
> По диаграмме:
> 
> * Вместо `List<что-то-там>` более архитектурно писать `что-то-там [*]`, вместо `Optional<что-то-там>` --- `что-то-там [0..1]`. Не надо привязываться к конкретному контейнеру раньше времени (разве что с Map это ок, потому что сам UML их не умеет --- точнее, умеет квалифицированные ассоциации, но это не всегда подходит).
> * Что-то я сомневаюсь, что всё, что у вас нарисовано как ассоциации, действительно ассоциации. Например, не исключено, что Parser `<<creates>>` CommandToken, и между ними просто зависимость (пунктиром). Ассоциация подразумевает поле.
> 
> Кстати, при запуске `gradlew test` оно просто пишет, что всё хорошо. А вроде как несложно сделать так, чтобы оно писало статистику по тестовому запуску --- сколько тестов всего, сколько прошло, сколько проигнорировано.
> 
> А ещё с `cat` что-то не то, `cat build.gradle | grep plugin` печатает весь build.gradle, а должен скармливать его следующей команде в пайпе.
> 
> И немного невнятные сообщения об ошибке:
> 
> ```
> $ grep -A test build.gradle
> For input string: "test"
> ```

Поправили:)

2022-03-06 12:38 UTC, yurii-litvinov approved these changes
Окей, зачтена

2022-03-06 12:38 UTC, yurii-litvinov commented on README.md
> +   3. [JOpt Simple](https://github.com/jopt-simple/jopt-simple) - недостаточно документации, не понятно как использовать
Если уж совсем хорошо делать, то надо изложить методику и критерии поиска. Например, что ввели в Google запрос "Разбор аргументов командной строки Java", посмотрели на первые пять ссылок выдачи, выбрали ту, с которой быстрее можно начать работать. Тогда будет понятно, что в спокойной обстановке можно выбрать более функциональную, лаконичную или даже быструю библиотеку.

2022-03-06 12:38 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/GrepCommand.java
> +            } catch (Exception e) {
Очень плохая идея ловить все исключения вообще. Потому как есть исключения, которые не должны быть пойманы. Правильнее посмотреть, какие исключения может бросать этот код, и ловить только те, которые реально можете обработать.

2022-03-07 20:23 UTC, merged