Hw 05
Soykaa/software-design-2022-hse pull request #19
Opened 2022-03-11 14:32 UTC by andreyshspb

2022-03-12 12:31 UTC, yurii-litvinov requested changes
```
$ ls ololo
Cannot read the array length because "<local6>" is null
```
И пользователь такой "Ааа, конечно же, с local6 что-то не так" :)) Диагностику допилите, пожалуйста.

А вот ещё интересное, и указывающее на более серьёзную ([хотя и легкоисправимую) проблему:
```
$ cd README.md
Can't find such directory
$ ls
Cannot read the array length because "<local6>" is null
$
```

2022-03-12 12:31 UTC, yurii-litvinov commented on REVIEW.md
> +# Реализация новых комманд
```suggestion
# Реализация новых команд
```

2022-03-12 12:31 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/Environment.java
> +     * @return path of current working directory
Правильнее без тэга `@return`, потому что без тэга комментарий в сгенерённой документации пойдёт в summary, а с тэгом — в детальное описание, в которое ещё попасть надо.

2022-03-12 12:31 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/LsCommand.java
> +        File fileName = new File(String.valueOf(path));
Лучше var, и ниже со StringBuilder тем более. Тем более что в остальном коде var-ы есть.

2022-03-12 12:31 UTC, yurii-litvinov commented on src/test/java/ru/hse/software/design/commands/CdCommandTests.java
> +        Command ls1 = new CdCommand(List.of("src"));
Команда cd, а называется ls1 — видимо, с копипастом что-то пошло не так :)

2022-03-12 12:31 UTC, yurii-litvinov commented on src/test/java/ru/hse/software/design/commands/LsCommandTest.java
> +        String expectedOutput;
А зачем оно так рано объявлено?

2022-03-12 12:31 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/CdCommand.java
> +            Environment.setCurrentFolderPath();
Так я ввожу `cd .. ..` и попадаю в домашнюю папку, а хотел бы получить ошибку, что слишком много параметров. Иначе это юзабилити-баг наподобие `rm -rf * .tmp`

2022-03-12 12:31 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/CdCommand.java
> +            errorStream.println("Command environment needs 0 or 1 argument");
Тут что-то пошло не так, `cd` не работает

2022-03-15 07:59 UTC, Atos1337 commented on src/main/java/ru/hse/software/design/commands/CdCommand.java
> +            errorStream.println("Command environment needs 0 or 1 argument");
Да, перепутал знак, добавил на это тест

2022-03-15 07:59 UTC, Atos1337 commented on src/main/java/ru/hse/software/design/commands/CdCommand.java
> +            Environment.setCurrentFolderPath();
Из-за баги со знаком, теперь тоже исправлено

2022-03-15 07:59 UTC, Atos1337 commented on src/test/java/ru/hse/software/design/commands/LsCommandTest.java
> +        String expectedOutput;
Исправлено

2022-03-15 07:59 UTC, Atos1337 commented on src/test/java/ru/hse/software/design/commands/CdCommandTests.java
> +        Command ls1 = new CdCommand(List.of("src"));
Исправлено

2022-03-15 08:00 UTC, Atos1337 commented on src/main/java/ru/hse/software/design/commands/LsCommand.java
> +        File fileName = new File(String.valueOf(path));
Исправлено

2022-03-15 08:00 UTC, Atos1337 commented on src/main/java/ru/hse/software/design/Environment.java
> +     * @return path of current working directory
Исправлено

2022-03-15 08:00 UTC, Atos1337 commented on REVIEW.md
> +# Реализация новых комманд
Исправлено

2022-03-15 08:00 UTC, Atos1337 commented
Самый верхний комментарий также исправлен

2022-06-18 10:49 UTC, yurii-litvinov commented
Да, теперь всё ок, зачтена

2022-06-19 13:19 UTC, merged