Hw02
Soykaa/software-design-2022-hse pull request #7
Opened 2022-02-04 16:43 UTC by JaneKirillova

2022-02-06 12:20 UTC, yurii-litvinov requested changes
gradlew.bat же вроде генерируется gradle, без него под Windows ваша инструкция по сборке не работает :) И, кстати, пять тестов под виндой не прошли, так что попрошу вас ещё поправить CI под Windows (сейчас он ничего содержательного не делает).

2022-02-06 12:20 UTC, yurii-litvinov commented on README.md
> +`echo [arguments]` - принимает на вод список аргументов, выводит их через пробел. В случае, если аргументы не переданы,
```suggestion
`echo [arguments]` - принимает на вход список аргументов, выводит их через пробел. В случае, если аргументы не переданы,
```

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/CLI.java
> + * which is set to true when the application is running and false when it terminates.
Это private-поле, его не надо рекламировать в видимом извне комментарии

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/CLI.java
> + * It has two main public methods 'start' and 'exit'
Это тоже довольно бессмысленно, и так понятно, какие методы у него есть. Вот написать, как ими пользоваться извне --- можно

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/CLI.java
> + * and private method 'createExecutor' responsible for creating an object of the Executor class.
Тут то же, что с isRunning --- 
- это никому извне не должно быть интересно
- зарефакторите класс, придётся не забыть править комментарий
- комментарий может быть воспринят как приглашение рефлексией метод повызывать

В общем, не надо :)

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/CLI.java
> +        CLI instance = new CLI();
```suggestion
        var instance = new CLI();
```
Хотя бывает мнение, что явный тип улучшает читабельность программы --- но тут он написан дважды, что точно излишество.

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/Environment.java
> +    private static final Map<String, String> envVariables = new HashMap<>();
Статические классы, как и синглтоны, сильно усложняют тестирование (вместо них свои заглушки не подставить) и не дают завести два шелла в одном процессе. Поэтому надо использовать их с большой осторожностью. Но дело вкуса, можно не править.

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/Executor.java
> +        this.path = new Path(System.getenv("PATH").split(":"));
Под Windows разделитель `;`, не надо лишней платформозависимости.

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/CatCommand.java
> +                errorStream.writeAsString("file " + commandArgs.get(0) + " does not exist");
Кажется, appendErrorMessage и errorStream.writeAsString всегда работают вместе. Стоило что-то с этим сделать.

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/Command.java
> +    protected OutputStream errorStream;
Лучше определить для Command конструктор, который бы инициализировал общие поля, чтобы во всех командах это не копипастить.

А потом пойти дальше и сделать поля private с protected-геттерами (но это уже опционально)

2022-02-06 12:20 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +                errorStream.writeAsString(e.getMessage());
У процесса свой errorStream, его надо писать в наш, даже если не было исключений

2022-02-07 20:19 UTC, Soykaa commented on src/main/java/ru/hse/software/design/CLI.java
> + * which is set to true when the application is running and false when it terminates.
Fixed

2022-02-07 20:19 UTC, Soykaa commented on src/main/java/ru/hse/software/design/CLI.java
> + * It has two main public methods 'start' and 'exit'
Fixed

2022-02-07 20:19 UTC, Soykaa commented on src/main/java/ru/hse/software/design/CLI.java
> + * and private method 'createExecutor' responsible for creating an object of the Executor class.
Fixed

2022-02-07 20:19 UTC, Soykaa commented on src/main/java/ru/hse/software/design/CLI.java
> +        CLI instance = new CLI();
Fixed)

2022-02-07 20:20 UTC, Soykaa commented on src/main/java/ru/hse/software/design/Executor.java
> +        this.path = new Path(System.getenv("PATH").split(":"));
Fixed

2022-02-07 21:12 UTC, Soykaa commented on README.md
> +`echo [arguments]` - принимает на вод список аргументов, выводит их через пробел. В случае, если аргументы не переданы,
Fixed

2022-02-08 15:52 UTC, Soykaa commented
Сейчас убрали все stream-ы, вместо них используются строки. Соответственно, все, что связано с последними тремя замечаниями работает несколько иначе

2022-02-10 10:49 UTC, yurii-litvinov requested changes
Надо немного доделать внешние процессы

2022-02-10 10:49 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/CLI.java
> +public class CLI {
```suggestion
 */
public class CLI {
```
Пустая строка обычно не ставится

2022-02-10 10:49 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/Parser.java
> +            if (insideDoubleQuotes | insideSingleQuotes) {
```suggestion
            if (insideDoubleQuotes || insideSingleQuotes) {
```

2022-02-10 10:49 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +        String[] envp = Environment.getAll();
Не сокращайте имена и чтите camelCase :)

2022-02-10 10:49 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/WCCommand.java
> +            errorStream.println("Command wc works with one file " + "or with standard input");
Гм

2022-02-10 10:49 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +            Process process = Runtime.getRuntime().exec(cmdarray, envp, new File(commandDirectory));
Не-а, так у вас процесс запускается не в текущей директории (pwd), а где лежит его бинарь. `git status` попробуйте.

2022-02-10 10:49 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +            if (new File(directory, command).exists()) {
Под виндой получается, что надо вводить не git, а git.exe, что неудобно. Кажется, ProcessBuilder сам может искать в PATH и знает про такие штуки. Может, стоит использовать его.

2022-02-10 13:52 UTC, Soykaa commented on src/main/java/ru/hse/software/design/CLI.java
> +public class CLI {
Fixed

2022-02-10 14:22 UTC, Soykaa commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +        String[] envp = Environment.getAll();
Fixed

2022-02-10 14:22 UTC, Soykaa commented on src/main/java/ru/hse/software/design/commands/WCCommand.java
> +            errorStream.println("Command wc works with one file " + "or with standard input");
да, действительно... fixed)

2022-02-10 14:28 UTC, Soykaa commented on src/main/java/ru/hse/software/design/Parser.java
> +            if (insideDoubleQuotes | insideSingleQuotes) {
Fixed

2022-02-10 23:23 UTC, Soykaa commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +            if (new File(directory, command).exists()) {
fixed

2022-02-11 13:08 UTC, Soykaa commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +            Process process = Runtime.getRuntime().exec(cmdarray, envp, new File(commandDirectory));
fixed

2022-02-11 14:07 UTC, yurii-litvinov requested changes
Теперь оно при запуске из консоли падает с тем, что не может найти бинарники от SystemUtils:
```
-----CLI interpreter-----
$ git
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemUtils
at ru.hse.software.design.commands.OuterCommand.<init>(OuterCommand.java:30)
at ru.hse.software.design.CommandBuilder.makeCommands(CommandBuilder.java:39)
at ru.hse.software.design.CommandBuilder.build(CommandBuilder.java:53)
at ru.hse.software.design.Executor.execute(Executor.java:35)
at ru.hse.software.design.CLI.start(CLI.java:42)
at ru.hse.software.design.CLI.main(CLI.java:20)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.SystemUtils
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
... 6 more                                                      
```
Подозреваю, что надо как-то более хитро паковать jar-ник, раз у вас добавились внешние зависимости.

2022-02-11 14:07 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +            commandName = commandName + ".exe";
Вообще, за неимением атрибута executable Windows считает исполнимыми все файлы, расширение которых есть в списке, задаваемом переменной окружения PATHEXT. На моём рабочем ноуте, например:
```
C:\>echo %PATHEXT%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW 
```
А командами assoc и ftype можно управлять, какая именно команда будет запускаться при запуске файла на исполнение. Так что нет, просто дописать .exe нехорошо :) Но это я скорее к тому, что жизнь боль --- думаю, что для первой домашки знать такие подробности устройства Windows вовсе не обязательно, сойдёт и так.

2022-02-11 14:07 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +        if (commandDirectory == null) {
А теперь вообще непонятно, зачем это :) Может быть так, что вы ругаетесь, а ProcessBuilder может успешно всё запустить. Правда, вы так старались с PATH-ом, а оказалось, что это не нужно.

2022-02-11 14:07 UTC, yurii-litvinov commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +                this.commandWithArguments.add("/C");
Костыль :) Если я `cmd /K` из вашего шелла захочу запустить, cmd скажет, что я неправ, что меня очень удивит, если я не знаю, что вы сами `/C` подставляете

2022-02-11 16:47 UTC, Soykaa commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +        if (commandDirectory == null) {
Fixed

2022-02-11 16:47 UTC, Soykaa commented on src/main/java/ru/hse/software/design/commands/OuterCommand.java
> +                this.commandWithArguments.add("/C");
То есть в данной ситуации подстановка `/C` -- на совести пользователя? Если так, то fixed

2022-02-11 17:03 UTC, Soykaa commented
> Подозреваю, что надо как-то более хитро паковать jar-ник, раз у вас добавились внешние зависимости.
Мы поняли, что там можно и без добавления зависимости обойтись, так что убрали ее. Вроде теперь должно работать

2022-02-11 17:50 UTC, yurii-litvinov approved these changes
👍

2022-02-11 18:05 UTC, merged